services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: company
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  employee-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql_data: